### ISSUE TITLE
Curses error when terminal is too small for interface

### ISSUE THREAD

**Issue by jag1g13** [jag1g13/pycgtool#16]
When the terminal is too small to fit the "--advanced" interface, curses throws an error that is not informative to the user.

Consider replacing the terminal interface with something based on Urwid (https://pypi.python.org/pypi/urwid/).

```
(env) james@smaug:~/projects/pycgtool$ ./pycgtool.py -g test/data/sugar.gro -m test/data/sugar.map --advanced
Traceback (most recent call last):
  File "./pycgtool.py", line 56, in <module>
    config.interactive()
  File "/home/james/projects/pycgtool/pycgtool/interface.py", line 117, in interactive
    curses.wrapper(self._inter)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/james/projects/pycgtool/pycgtool/interface.py", line 149, in _inter
    text_edit_wins.append(window_vals.derwin(1, 30, i, 0))
_curses.error: curses function returned NULL

```

**Comment by jag1g13** [comment]
Added meaningful error message in 08b193b.
