### ISSUE TITLE
Error in numba.jit function declaration types

### ISSUE THREAD

**Issue by MaryamSSadeghi** [jag1g13/pycgtool#45]
Hello, 
I'm trying to use pycgtool to get the MARTINI valence parameters for a small molecule, following the pycgtool tutorial on https://pycgtool.readthedocs.io/en/master/tutorial.html. I've made the map and bonding index files according to the tutorial, but when I run the code, I get the following error:
Traceback (most recent call last):
  File "pycgtool.py", line 7, in <module>
    from pycgtool.pycgtool import main, map_only
  File "/media/maryam/Maryam_Files/3_mapped/PYCGTOOL/pycgtool/pycgtool.py", line 3, in <module>
    from .frame import Frame
  File "/media/maryam/Maryam_Files/3_mapped/PYCGTOOL/pycgtool/frame.py", line 12, in <module>
    from .util import backup_file
  File "/media/maryam/Maryam_Files/3_mapped/PYCGTOOL/pycgtool/util.py", line 54, in <module>
    @numba.jit(numba.float32[3](numba.float32[3], numba.float32[3]))
  File "/home/maryam/anaconda3/lib/python3.8/site-packages/numba/core/types/abstract.py", line 186, in __getitem__
    ndim, layout = self._determine_array_spec(args)
  File "/home/maryam/anaconda3/lib/python3.8/site-packages/numba/core/types/abstract.py", line 211, in _determine_array_spec
    raise KeyError(f"Can only index numba types with slices with no start or stop, got {args}.")
KeyError: 'Can only index numba types with slices with no start or stop, got 3.'

**Comment by jag1g13** [comment]
Hi, thanks for letting me know about this error - it looks like there might have been an update to Numba which has changed how it should be used.

I've been preparing to release PyCGTOOL version 2 soon, which doesn't use Numba, so should fix this problem for you. You can install the new version already by using `pip install pycgtool==2.0.0b1`. The mapping and bond files you have will work with the new version, but the commands have some very small differences which you can see at https://pycgtool.readthedocs.io/en/dev/tutorial.html.

**Comment by MaryamSSadeghi** [comment]
It's working, thank you.
